{% set name = "zenodo_backpack" %}
{% set version = "0.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 577f66dbe59512f31dab7d5d61a2f65c6a7e8e91a8cf57a2d02e3d2ebe091c6d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests
    - tqdm

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - zenodo_backpack

about:
  home: "https://github.com/centre-for-microbiome-research/zenodo_backpack"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: "Manage data bundled with bioinformatic software through Zenodo DOI integration"
  doc_url: "https://github.com/centre-for-microbiome-research/zenodo_backpack"
  dev_url: "https://github.com/centre-for-microbiome-research/zenodo_backpack"

extra:
  recipe-maintainers:
    - chklovski
