{% set name = "zenodo_backpack" %}
{% set version = "0.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: dc91f3c427f976465789746e94736abfa536cf42dc2e49b6d6067382a9a39b26

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - requests
    - tqdm

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - zenodo_backpack

about:
  home: "https://github.com/centre-for-microbiome-research/zenodo_backpack"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: "Manage data bundled with bioinformatic software through Zenodo DOI integration"
  doc_url: "https://github.com/centre-for-microbiome-research/zenodo_backpack"
  dev_url: "https://github.com/centre-for-microbiome-research/zenodo_backpack"

extra:
  recipe-maintainers:
    - wwood
    - chklovski
